version: '3'
services:
  app:
    container_name: checkout_app
    build: .
    ports: 
      - 9000:9000 
    restart: on-failure
    depends_on:
      - database 
    networks:
      - dockernet

  database:
    image: "postgres" 
    container_name: checkout_app_db
    env_file:
      - config/database.env 
    networks:
      - dockernet
    ports:
      - 5432:5432
    volumes:
      - ./files/sql_script/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

networks:
  dockernet:
    driver: bridge